comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('<int:video_type>/comment_home', views.comment_home, name = 'comment_home'),
    path('<int:video_id>/comment_main/', views.comment_main, name = 'comment_main'),
    path('<int:cmt_id>/delete/', views.delete_comment, name = 'delete_comment'),
    # path('<int:report_id>/update/', views.detail_report, name = 'detail_report'),
]

main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.login_view),
    path('logout/', views.logoutPage, name='logout'),
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('report/', include('report.urls')),
    path('category/', include('category.urls')),
    path('', include('managervideo.urls')),
    path('setting/', include('settingweb.urls')),
    path('comment/', include('comment.urls')),
    path('video/', include('videoapp.urls')),
    path('notification/', include('notification.urls')),
]

comment/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import main.base64_change as bs
from django.core.paginator import Paginator
from Constant import SERVER_URL
import json
import requests

def decode_Item_Cmt(comment):
    comment['uid'] = bs.decode_Str(comment['uid'])
    comment['cmt_text'] = bs.decode_Str(comment['cmt_text'])
    
    return comment

def decode_Cmt(comments):
    for comment in comments:
        comment = decode_Item_Cmt(comment)
    return comments

def decode_Item_Vid(video):
    video['vid_title'] = bs.decode_Str(video['vid_title'])
    return video

def decode_Vid(videos):
    for video in videos:
        video = decode_Item_Vid(video)
    return videos

@login_required(login_url='/login')
def comment_home(request, video_type):
    video_search = request.GET.get('tv_search_video') if request.GET.get('tv_search_video') != None else ''
    postObj = {
        'method_name': 'LOAD_ALL_VID_CMT',
        'vid_search': bs.encode_Str(video_search),
        'vid_type': video_type,
    }
    data = {
        'data': json.dumps(postObj),
    }
    res = requests.post(SERVER_URL, data=data)
    return_object = json.loads(res.content)

    list_vid = decode_Vid(return_object['list'])

    #Paginator
    p = Paginator(list_vid, 8)
    page = request.GET.get('page') 
    list_vids = p.get_page(page)
    nums = "a" * list_vids.paginator.num_pages

    context = {'list_vids': list_vids, 'video_type':video_type, 'nums':nums}
    return render(request, 'comment/home_comment.html', context)

@login_required(login_url='/login')
def comment_main(request, video_id):
    cmt_search = request.GET.get('tv_search_cmt') if request.GET.get('tv_search_cmt') != None else ''
    postObj = {
        'method_name': 'LOAD_CMT_BY_VID_SEARCH',
        'vid_id': video_id,
        'cmt_search': bs.encode_Str(cmt_search),
    }
    data = {
        'data': json.dumps(postObj),
    }
    res = requests.post(SERVER_URL, data=data)
    return_object = json.loads(res.content)

    cmts = decode_Cmt(return_object['list'])
    Paginator
    p = Paginator(cmts, 8)
    page = request.GET.get('page') 
    list_cmts = p.get_page(page)
    nums = "a" * list_cmts.paginator.num_pages

    if (list_cmts is not None):
        context = {
            
            'video_cat' : bs.decode_Str(list_cmts[0]['cat_name']), 
            'video_title' : bs.decode_Str(list_cmts[0]['vid_title']), 
            'video_id': list_cmts[0]['vid_id'],
            'vid_view': list_cmts[0]['vid_view'],
            'total_comments' : list_cmts[0]['total_comments'], 
            'nums': nums,
            'list_cmts': list_cmts,
        }
        return render(request, 'comment/list_comment.html', context)
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    

        

def delete_comment(request, cmt_id):
    
    if request.method=="POST":
        postObj = {
        'method_name': 'DEL_CMT',
        'cmt_id': cmt_id,
        }
        data = {
            'data': json.dumps(postObj),
        }
        res = requests.post(SERVER_URL, data=data)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

comment/templates/comment/home_comment.html
{% extends 'main.html' %} 
{% load static %} 
{% block content %} 
<nav class="navbar bg-light" style="top: 1%;">
  <div class="container-fluid">
    <div class="dropdown">
        <select class="choice-type btn  btn-dark" name="type" select = "4" size = "1" onchange = "window.location.href =  this.value">
          <option value="{% url 'comment:comment_home' 0 %}"
            {% if video_type == 0 %} selected = "selected" {% endif %}>All</option>
          <option value="{% url 'comment:comment_home' 1 %}"
            {% if video_type == 1 %} selected = "selected" {% endif %}>Video</option>
          <option value="{% url 'comment:comment_home' 2 %}" 
            {% if video_type == 2 %} selected = "selected" {% endif %}>Live TV</option>
          <option value="{% url 'comment:comment_home' 3 %}"
            {% if video_type == 3 %} selected = "selected" {% endif %}>Radio</optoion>
        </select>
      </div>
    <form class="d-flex" role="search" method="GET" action="{% url 'comment:comment_home' video_type%}"> {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search or All" aria-label="Search" name="tv_search_video">
      <button class="btn btn-outline-success" type="submit" name="btn_search_video" style="margin-left:5px;">Search</button>
    </form>
  </div>
</nav>
<table class="table table_report" style = "overflow-y:scroll; height:75vh">
  <thead class="thead-light">
    <tr>
      <th scope="col">Video ID</th>
      <th scope="col">Video Title</th>
      <th scope="col">Total Comments</th>
      <th scope="col"></th>
    </tr>
  </thead>
  
  
  <tbody >
    {% for x in list_vids %}
    <tr>
      <td>{{x.vid_id}}</td>
      <td>{{x.vid_title}}</td>
      <td>{{x.total_cmts}}</td>
      <td>
        <form action="{% url 'comment:comment_main' x.vid_id %}">
          <input type="image" class="icon_report" src="{% static 'styles/images/more.png' %}" />
        </form>
      </td>
    </tr>
  </tbody>
  {% endfor %} 
</table>
<nav aria-label="Page navigation example " style="margin-top: 10px;">
  <ul class="pagination">
    {% if list_vids.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_vids.previous_page_number}}">Previous</a></li>
    {% endif %}
    {% for i in nums %}
    <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}
    {% if list_vids.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{list_vids.next_page_number}}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_vids.paginator.num_pages}}">Last &raquo</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

comment/templates/comment/list_comment.html
{% extends 'main.html' %} 
{% load static %} 
{% block content %}
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold">{{video_title}}</a>
    <form class="d-flex" role="search" method="GET" action="{% url 'comment:comment_main' video_id %}"> {% csrf_token %}
      <input class="form-control me-2" type="search" name="tv_search_cmt" placeholder="Search or All" aria-label="Search">
      <button class="btn btn-outline-success" name="btn_search_cmt" type="submit">Search</button>
    </form>
  </div>
</nav>
<div style = "overflow-y:scroll; height:82vh">
<ol class="list-group list-group-numbered border border-primary">
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Video Category</div>
      {{video_cat}}
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Video Views</div>
      {{vid_view}}
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Total Comments</div>
      {{total_comments}}
    </div>
  </li>
</ol>

<div>


<div class="list-group border border-primary" style="margin-top: 20px">
    {% for cmt in list_cmts %}
  <li class="list-group-item ">
    <div class="row g-3">
      <div class="col-md-1 d-flex justify-content-center align-items-center">
        <input
          type="image"
          class="icon_user"
          src="{% static 'styles/images/user.png' %}"
        />
      </div>
      <div class="col-md-11 ">
        <div class="d-flex w-100 justify-content-between align-items-center">
          <h6 >{{cmt.uid}}</h6>
          <p style="font-size:12px;">{{cmt.cmt_time}}</p>
        </div>
        <div class="d-flex w-100 justify-content-between align-items-center">
            <p>{{cmt.cmt_text}}</p>
            <input type="image" class="icon_report" src="{% static 'styles/images/delete.png' %}" data-bs-toggle="modal" data-bs-target="#mymodal{{cmt.cmt_id}}" class="icon_report" />
          <div
            class="modal fade"
            id="mymodal{{cmt.cmt_id}}"
            tabindex="-1"
            role="dialog"
            aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true"
            
          >
            <div class="modal-dialog modal-dialog-centered" role="document" id="a{{cmt.cmt_id}}">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="b{{cmt.cmt_id}}">
                    Are you sure you want to delete comment of user {{cmt.uid}} at {{cmt.cmt_time}} ?
                  </h5>
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">{{cmt.cmt_text}} </div>
                <div class="modal-footer">
                  <form action="{% url 'comment:delete_comment' cmt.cmt_id %}"  method="POST"> {% csrf_token %}
                  <button type="submit" class="btn btn-primary">Yes</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
       
      </div>
    </div>
  </li>
  {% endfor %}



</div>

</div>

</div>
<nav aria-label="Page navigation example " style="margin-top: 10px;">
  <ul class="pagination">
    {% if list_cmts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_cmts.previous_page_number}}">Previous</a></li>
    {% endif %}
    {% for i in nums %}
    <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}
    {% if list_cmts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{list_cmts.next_page_number}}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_cmts.paginator.num_pages}}">Last &raquo</a></li>
    {% endif %}
  </ul>
</nav>


{% endblock %}