main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.login_view),
    path('logout/', views.logoutPage, name='logout'),
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('report/', include('report.urls')),
    path('category/', include('category.urls')),
    path('', include('managervideo.urls')),
    path('setting/', include('settingweb.urls')),
    path('comment/', include('comment.urls')),
    path('video/', include('videoapp.urls')),
    path('notification/', include('notification.urls')),
]

managervideo/urls.py
from django.urls import path
from . import views
app_name = 'managervideo'
urlpatterns = [
    path('managervideo/<str:pk>/<int:cat>/', views.managervideo, name='managervideo'),
    path('managervideo/add/<str:pk>/<int:cat>/', views.addTv, name='addvideo'),
    path('managervideo/edit/<str:pk>/<int:cat>/<str:id>/', views.editTv, name='editvideo'),
    path('managervideo/disable/<str:pk>/<int:cat>/<str:id>/', views.disableVideo, name='disablevideo'),
]

videoapp/urls.py
from django.urls import path
from . import views

app_name = "videoapp"

urlpatterns = [
    path('detail/<str:id>/', views.updateVideo, name='update'),
    path('create/', views.createVideo, name='create'),
    path('player/', views.videoPlayer, name='player'),
]

managervideo/views.py
import json
import requests as rq
from django.contrib import messages
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
import main.base64_change as bs
from datetime import date
import base64
from django.core.paginator import Paginator
from Constant import SERVER_URL
import requests
import json
# Create your views here.

def decode_Item_cate(category):
    category['cat_id'] = int(category['cat_id'])
    category['cat_name'] = bs.decode_Str(category['cat_name'])
    category['cat_image'] = bs.decode_Str(category['cat_image'])
    category['cat_type'] = int(category['cat_type'])
    category['cat_status'] = int(category['cat_status'])
    return category

def decode_Cate(categories):
    for category in categories:
        category = decode_Item_cate(category)
    return categories

def decode_Item_Video(video):
    video['vid_id'] = int(video['vid_id'])
    video['cat_id'] = int(video['cat_id'])
    video['vid_title'] = bs.decode_Str(video['vid_title'])
    video['vid_url'] = bs.decode_Str(video['vid_url'])
    video['vid_thumbnail'] = bs.decode_Str(video['vid_thumbnail'])
    video['vid_description'] = bs.decode_Str(video['vid_description'])
    video['vid_view'] = int(video['vid_view'])
    video['vid_duration'] = int(video['vid_duration'])
    video['vid_avg_rate'] = float(video['vid_avg_rate'])
    video['vid_status'] = int(video['vid_status'])
    video['vid_type'] = int(video['vid_type'])
    video['vid_is_premium'] = int(video['vid_is_premium'])
    return video

def decode_Video(videos):
    for video in videos:
        video = decode_Item_Video(video)
    return videos

def getVid(id):
    postObj = {
        'method_name': 'GET_VIDEO_BYID',
        'vid_id': id
    }

    data = {
        'data': json.dumps(postObj)
    }

    res = requests.post(SERVER_URL , data = data)
    return_obj = json.loads(res.content)

    return return_obj['video'] if return_obj['status'] == "success" else []

@login_required(login_url='/login')
def managervideo(request , pk, cat):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    postObj = {
        'method_name': 'LOAD_TV_OR_RADIO',
        'type':pk,
        'cate_id':cat,
        'search_txt': q
    }

    data = {
        'data': json.dumps(postObj)
    }

    res = requests.post(SERVER_URL , data = data)
    return_obj = json.loads(res.content)

    videos = return_obj['all'] if return_obj['status'] == "success" else []
    categories = return_obj['category'] if return_obj['status'] == "success" else []
    videos = decode_Video(videos)
    categories = decode_Cate(categories)
    #Paginator
    p = Paginator(videos, 8)
    page = request.GET.get('page') 
    list_res = p.get_page(page)
    nums = "a" * list_res.paginator.num_pages
    context = {'choice':pk, 'cat':cat, 'categories':categories, 'videos':list_res, 'test':q, 'nums':nums}
    return render(request, 'managervideo/managervideo.html', context)

@login_required(login_url='/login')
def addTv(request, pk, cat):
    postObj = {
        'method_name': 'LOAD_CATEGORT',
        'type':pk,
        'search_txt': ''
    }

    data = {
        'data': json.dumps(postObj)
    }

    res = requests.post(SERVER_URL , data = data)
    return_obj = json.loads(res.content)

    categories = return_obj['category'] if return_obj['status'] == "success" else []
    categories = decode_Cate(categories)
    if request.method == 'POST':

        if 'file_img' in request.FILES:
            print("update image")

            url = SERVER_URL + '/uploadImage.php'
            files = {'file': request.FILES['file_img']}
            data = {'crr': request.POST.get('thumbnail')}
            res = rq.post(url, files=files, params=data)
        
            js = json.loads(res.content)
            if(js['status'] == 1):
                image_dir = SERVER_URL + '/image/'+js['dir'];
                thumbnail = base64.b64encode(image_dir.encode('utf-8')).decode('utf-8')
            else:
                messages.error(request, "Something wrong when upload image, please try again!")
                return redirect('videoapp:create')
        else:
            messages.error(request, "Thumbnail is required!")
            return redirect('videoapp:create')

        postObj =  {
                    'method_name': 'ADD_VIDEO',
                    'cat_id':request.POST.get('category_vid'),
                    'vid_title': bs.encode_Str(request.POST.get('title')),
                    'vid_url': bs.encode_Str(request.POST.get('url')), 
                    'vid_thumbnail': thumbnail,
                    'vid_description': bs.encode_Str(request.POST.get('description')), 
                    'vid_view': "0", 
                    'vid_duration': "0", 
                    'vid_time': request.POST.get('time'), 
                    'vid_avg_rate': "0", 
                    'vid_status': request.POST.get('vid_status'), 
                    'vid_type': pk,
                    'vid_is_premium': "0"}
        data = {
            'data': json.dumps(postObj)
        }
        res = requests.post(SERVER_URL , data = data)
        return_obj = json.loads(res.content)
        if str(return_obj) == "success":
            return redirect("managervideo:managervideo", pk, request.POST.get('category_vid'))
        else:
            return HttpResponse("Error")
    else:   
        date_time = date.today().strftime("%Y-%m-%d")
        page = 'add'
        context = {'page': page, 'choice':pk, 'cat':cat, 'date_time':date_time, 'categories':categories, 'mode': 'create'}
        return render(request, 'managervideo/tvradiodetail.html', context)

@login_required(login_url='/login')
def editTv(request, pk, cat, id):
    video = getVid(id)
    video = decode_Item_Video(video)
    date_time = (datetime.strptime(video['vid_time'], "%Y-%m-%d %H:%M:%S")).strftime('%Y-%m-%d')

    postObj = {
        'method_name': 'LOAD_CATEGORT',
        'type':pk,
        'search_txt': ''
    }

    data = {
        'data': json.dumps(postObj)
    }

    res = requests.post(SERVER_URL , data = data)
    return_obj = json.loads(res.content)

    categories = return_obj['category'] if return_obj['status'] == "success" else []
    categories = decode_Cate(categories)

    if request.method == 'POST':

        thumbnail = bs.encode_Str(request.POST.get('thumbnail'))

        #check user update image
        if 'file_img' in request.FILES:
            print("update imageeeeeeeeeeeeeeeeeee")

            url = SERVER_URL + '/uploadImage.php'
            files = {'file': request.FILES['file_img']}
            data = {'crr': request.POST.get('thumbnail')}
            res = rq.post(url, files=files, params=data)
        
            js = json.loads(res.content)
            if(js['status'] == 1):
                image_dir = SERVER_URL + '/image/'+js['dir'];
                thumbnail = base64.b64encode(image_dir.encode('utf-8')).decode('utf-8')
            else:
                messages.error(request, "Something wrong when upload image, please try again!")
                return redirect('managervideo:editvideo', cat=cat, id=id)

        postObj = {
            'method_name': 'UPDATE_VIDEO','vid_id': video['vid_id'],
            'cat_id': request.POST.get('category_vid'),
            'vid_title': bs.encode_Str(request.POST.get('title')), 
            'vid_url': bs.encode_Str(request.POST.get('url')), 
            'vid_thumbnail': thumbnail,
            'vid_description': bs.encode_Str(request.POST.get('description')), 
            'vid_view': request.POST.get('views'),
            'vid_duration': video['vid_duration'],
            'vid_time': request.POST.get('time'),
            'vid_avg_rate': request.POST.get('rate'),
            'vid_status': request.POST.get('vid_status'), 
            'vid_type': pk,
            'vid_is_premium': "0"}

        data = {
            'data': json.dumps(postObj)
        }
        res = requests.post(SERVER_URL , data = data)
        return_obj = json.loads(res.content)
        if str(return_obj) == "success":
            return redirect("managervideo:managervideo", pk, request.POST.get('category_vid'))
        else:
            return HttpResponse("Error")
    else:
        page = 'edit'
        context = {'page': page, 'choice':pk, 'cat':cat, 'video':video, 'categories':categories, 'date_time':date_time, 'mode': 'update'}
        return render(request, 'managervideo/tvradiodetail.html', context)

@login_required(login_url='/login')
def disableVideo(request, pk, cat, id):
    video = getVid(id)
    postObj = {
        'method_name': 'UPDATE_STATUS_RADIOTV',
        'vid_id': id,
        'status': 1 if video['vid_status'] == '0' else 0
    }

    data = {
        'data': json.dumps(postObj)
    }
    res = requests.post(SERVER_URL , data = data)
    return redirect("managervideo:managervideo", pk, cat)

templates/managervideo/managervideo.html
{% extends 'main.html' %} {% load static %} {% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'styles/category/category.css' %}"
/>
{% endblock style%}
{% block title %}Manager Video{% endblock title %} 
{% block content %}
<div>
  <div class="taskbar_category" >
    <select class="form-select" style="width:15%;" name="type" select = "2" size = "1" onchange = "window.location.href =  this.value">
      <option value="{% url 'managervideo:managervideo' pk=1 cat=0%}"
        {% if choice == "1"%} selected = "selected" {%endif%}>Video</option>
      <option value="{% url 'managervideo:managervideo' pk=2 cat=0%}" 
        {% if choice == "2"%} selected = "selected" {%endif%}>Live TV</option>
      <option value="{% url 'managervideo:managervideo' pk=3 cat=0%}"
        {% if choice == "3"%} selected = "selected" {%endif%}>Radio</optoion>
    </select>
    <select class="form-select" style="width:15%; margin-left:10px;" name="cate" select = "2" size = "1" onchange = "window.location.href =  this.value">
      <option value="{% url 'managervideo:managervideo' pk=choice cat=0%}">All Category</option>
      {% for category in categories %}

        <option value="{% url 'managervideo:managervideo' pk=choice cat=category.cat_id%}"
        {% if category.cat_id == cat  %} selected="selected"{% endif %}>{{category.cat_name}}</option>
          
      {% endfor %}
    </select>
    <a type="button b" style="margin-left:10px;"
    {% if choice == "1"%} 
      href="{% url 'videoapp:create' %}" 
    {% else %}
      href = "{% url 'managervideo:addvideo' pk=choice cat=cat%}"
    {% endif %}
    class="btn btn-dark">NEW VIDEO</a>
    <div class="d-flex flex-row ms-auto" style="margin-right:2%">
      <form action="{% url 'managervideo:managervideo' pk=choice cat=cat %}" method = "GET">
        <input class="input-group-text" type="text" name = "q" placeholder = "Search Video...."/>
      </form>
    </div>
  </div>

  <div style="height: 90vh; margin-left:30px;" >
    <div style = "height: 92%; overflow-y:scroll">
      <div class="row content_category" >
        {% for video in videos %}
        <div
          class="card"
          style="
            width: 20%;
            height: 100%;
            padding-left: 15px;
            padding-right: 15px;
            padding-top: 15px;
            padding-bottom: 15px;
            margin-left: 30px;
            margin-bottom: 20px;
          "
        >
          <div
          style = "
            height:100%;
            position: relative;
            overflow: hidden;
          "
          class="card-img-top">
            <img  src="{{video.vid_thumbnail}}" 
            style = "
              position: absolute;
              left: 50%;
              top: 50%;
              min-height: 100%;
              width: 100%;
              -webkit-transform: translate(-50%,-50%);
                  -ms-transform: translate(-50%,-50%);
                      transform: translate(-50%,-50%);
            " />
          </div>
          <div class="card-body" style="padding:5px; margin-top:2px;">
            <h5 class="card-title">{{video.vid_title}}</h5>
            <a type="button"
            {% if choice == "1"%} 
              href="{% url 'videoapp:update' video.vid_id %}" 
            {% else %}
              href = "{% url 'managervideo:editvideo' pk=choice cat=cat id=video.vid_id%}"
            {% endif %} class="btn btn-primary btn-sm">Edit</a>
            <a type="button" href = "{% url 'managervideo:disablevideo' pk=choice cat=cat id=video.vid_id  %}" 
              class=" {% if video.vid_status == 1 %}btn btn-primary btn-sm{% else %}btn btn-secondary btn-sm{% endif %} ">
              {% if video.vid_status == 1%}
                  Disable
              {%else%}
                  Enable
              {%endif%}
            </a>
          
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="d-flex justify-content-center align-items-center" style="height: 8%">
      <nav aria-label="Page navigation example ">
        <ul class="pagination">
          {% if videos.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{videos.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in nums %}
          <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
          {% endfor %}
          {% if videos.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{videos.next_page_number}}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{videos.paginator.num_pages}}">Last &raquo</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>



</div>
{% endblock content %}

templates/managervideo/tvradiodetail.html
{% extends 'main.html' %}

{% block title %}
    {% if page == 'add'%}
        ADD SOURCE  
    {% else %}
        EDIT SOURCE
    {%endif%}
{% endblock title %}

{% block content %}


<div class="card border-dark bg-light my-1">
    <p class="card-header h3 text-white bg-dark">
        {%if page == 'add'%}
            ADD 
            {%if choice == "2"%}
                TV
            {%elif choice == "3"%}
                RADIO
            {%endif%}
        {% else %}
            {%if choice == "2"%}
                TV
            {%elif choice == "3"%}
                RADIO
            {%endif%} DETAIL
        {% endif %}
    </p>

    <form id="form_update" method="post" enctype="multipart/form-data" action="" class="fw-bold p-4">
        {% csrf_token %}
        <div class="d-flex mb-3 justify-content-center align-items-center bg-secondary border border-primary rounded">
            <img id="image" class="w-25 " alt="Can't show that picture" src="{% if mode == 'create' %}https://socialistmodernism.com/wp-content/uploads/2017/07/placeholder-image.png?w=640{% else %} {{video.vid_thumbnail}} {% endif %}"/>
        </div>
        <div class="mb-3">
            <label for="fromFile" class="form-label">Thumbnail</label>
            <div>
                <input id="image_picker" accept="image/*" class="form-control" name="file_img" type="file" id="formFile">
            </div>
            <input type="hidden" name="thumbnail" value="{{video.vid_thumbnail}}"/>
        </div>

        <div class="mb-3">
            <label class="form-label" for="exampleFormControlInput1">Title</label>
            <input
                name="title"
                type="text"
                value="{{video.vid_title}}"
                class="form-control"
                required
                id="exampleFormControlInput1"
            />
        </div>

        {%if page == 'edit'%}
        <div class="mb-3 row g-3">
            <div class="form-group col-md-4">
                <label class="form-label" for="exampleFormControlInput1">ID</label>
                <input
                    name="id"
                    type="number"
                    value="{{video.vid_id}}"
                    class="form-control"
                    required
                    id="exampleFormControlInput1"
                    readonly="readonly"
                />
            </div>
            <div class="form-group col-md-4">
                <label class="form-label" for="exampleFormControlInput1">Rate average</label>
                <input
                    name="rate"
                    type="number"
                    min="0"
                    value="{{video.vid_avg_rate}}"
                    required
                    readonly="readonly"
                    class="form-control"
                    id="exampleFormControlInput1"
                />
            </div>
        </div>
        {%endif%}
        <div class="mb-3">
            <label class="form-label" for="exampleFormControlSelect1">Category</label>
            <select class="form-control" name='category_vid' id="exampleFormControlSelect1">
                {% for category in categories %}

                <option name="cat_id" value="{{category.cat_id}}" {% if category.cat_id == video.cat_id  %} selected="selected"{% endif %}>{{category.cat_name}}</option>

                
                {% endfor %}
            </select>
        </div>
    
        <label class="d-block form-label" for="exampleFormControlInput1">URL</label>    
        <div class="row g-3 mb-3">
            <div class="form-group col">
                <input
                    id="txt_url"
                    name="url"
                    type="text"
                    class="d-inline form-control"
                    value="{{video.vid_url}}"
                    required
                    id="exampleFormControlInput1"
                />
            </div>
          </div>
        
        <div class="form-group mb-3">
            <label class="form-label" for="exampleFormControlTextarea1">Description</label>
            <textarea
                name="description"
                class="form-control"
                id="exampleFormControlTextarea1"
                required
                rows="6"
            >{{video.vid_description}}</textarea>
        </div>
        <div class="row g-3 mb-3">
            {% if page == 'edit'%}
            <div class="form-group col-md-6">
                <label class="form-label" for="exampleFormControlInput1">Views</label>
                <input
                    name="views"
                    type="number"
                    min="0"
                    step="1"
                    required
                    class="form-control"
                    value="{{video.vid_view}}"
                    id="exampleFormControlInput1"
                />
            </div>
            {%endif%}
            <div class="form-group col-md-6">
                <label class="form-label" for="exampleFormControlInput1">Post time</label>
                <input
                    name="time"
                    type="date"
                    class="form-control"
                    value="{{date_time}}"
                    id="exampleFormControlInput1"
                />
            </div>
        </div>
        <div class="form-group">
            <label class="form-label" for="exampleFormControlSelect1">Status</label>
            <select class="form-control" name="vid_status" id="exampleFormControlSelect1">

                {% if video.vid_status == 1 %}
                <option name="status" value="1" selected="selected">Enable</option>
                <option name="status" value="0">Disable</option>
                {% else %}
                <option name="status" value="1">Enable</option>
                <option name="status" value="0" selected="selected">Disable</option>
                {% endif %}

            </select>
        </div>

        <div
            class="d-flex mt-5 flex-row justify-content-end align-items-center"
        >
            <input type="submit" onclick="save()" class="btn btn-primary me-2" value="Save"/>
            <a type="button" href="{% url 'managervideo:managervideo' pk=choice cat=cat%}" class="btn btn-danger" value="Cancel">Cancel</a>
        </div>
    </form>
    <form id="form_check" method="post" action="">
        {% csrf_token %}
        <input type="hidden" name="url" id="hidden_url">
    </form>
</div>

<script>


    form_update = document.getElementById("form_update");

    form_check = document.getElementById("form_check");
    hidden_url = document.getElementById("hidden_url");

    form_check.onsubmit = function(e){
        e.preventDefault();
    }

    form_update.onsubmit = function(e){
       e.preventDefault();
    }

    document.getElementById("image_picker").onchange = function () {
        var reader = new FileReader();
    
        reader.onload = function (e) {
            // get loaded data and render thumbnail.
            document.getElementById("image").src = e.target.result;
        };
    
        // read the image file as a data URL.
        reader.readAsDataURL(this.files[0]);
    };

    function save() {

        if (confirm("Please confirm your action!") == true) {
            form_update.submit();
        }

    }

    function validURL(str) {
        var pattern = new RegExp('^(https?:\\/\\/)?'+ // protocol
          '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|'+ // domain name
          '((\\d{1,3}\\.){3}\\d{1,3}))'+ // OR ip (v4) address
          '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+ // port and path
          '(\\?[;&a-z\\d%_.~+=-]*)?'+ // query string
          '(\\#[-a-z\\d_]*)?$','i'); // fragment locator
        return !!pattern.test(str);
      }
</script>

{% endblock content %}