main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.login_view),
    path('logout/', views.logoutPage, name='logout'),
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('report/', include('report.urls')),
    path('category/', include('category.urls')),
    path('', include('managervideo.urls')),
    path('setting/', include('settingweb.urls')),
    path('comment/', include('comment.urls')),
    path('video/', include('videoapp.urls')),
    path('notification/', include('notification.urls')),
]

report/urls.py
from django.urls import path
from report import views

app_name = 'report'
urlpatterns = [
    path('<int:video_type>/report_home', views.report_home, name = 'report_home'),
    path('<int:video_id>/report_main/', views.report_main, name = 'report_main'),
    path('<int:report_id>/update/', views.detail_report, name = 'detail_report'),
    path('<int:report_id>/delete/', views.delete_report, name = 'delete_report'),
]

report/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import main.base64_change as bs
from django.core.paginator import Paginator
from Constant import SERVER_URL
import json
import requests

def decode_Item_Report(report):
    report['uid']= bs.decode_Str(report['uid'])
    report['report_content'] = bs.decode_Str(report['report_content'])
    return report

def decode_Report(reports):
    for report in reports:
        report = decode_Item_Report(report)
    return reports

def decode_Item_Vid(video):
    video['vid_title'] = bs.decode_Str(video['vid_title'])
    return video

def decode_Vid(videos):
    for video in videos:
        video = decode_Item_Vid( video )
    return videos

@login_required(login_url='/login')
def report_home(request, video_type):
    video_search = request.GET.get('tv_search_video') if request.GET.get('tv_search_video') != None else ''
    postObj = {
        'method_name': 'LOAD_ALL_VID_REPORT',
        'vid_search': bs.encode_Str(video_search),
        'vid_type': video_type,
    }
    data = {
        'data': json.dumps(postObj),
    }
    res = requests.post(SERVER_URL, data=data)
    return_object = json.loads(res.content)

    list_vid = decode_Vid(return_object['list'])

    Paginator
    p = Paginator(list_vid, 8)
    page = request.GET.get('page') 
    list_vids = p.get_page(page)
    nums = "a" * list_vids.paginator.num_pages

    context = {'list_vids':list_vids, 'video_type':video_type, 'nums':nums}
    return render(request, 'report/home_report.html', context)

@login_required(login_url='/login')
def report_main(request, video_id):
    report_search = request.GET.get('tv_search_report') if request.GET.get('tv_search_report') != None else ''
    postObj = {
        'method_name': 'LOAD_REPORT_BY_VID',
        'vid_id': video_id,
        'report_search': bs.encode_Str(report_search),
    }
    data = {
        'data': json.dumps(postObj),
    }
    res = requests.post(SERVER_URL, data=data)
    return_object = json.loads(res.content)

    reports = decode_Report(return_object['list'])

    Paginator
    p = Paginator(reports, 8)
    page = request.GET.get('page') 
    list_res = p.get_page(page)
    nums = "a" * list_res.paginator.num_pages

    context = {'video_id':video_id, 'list_res':list_res, 'nums': nums }
    return render(request, 'report/list_report.html', context)

@login_required(login_url='/login')
def detail_report(request, report_id):
    postObj = {
        'method_name': 'LOAD_DETAIL_REPORT',
        'report_id': report_id,
    }
    data = {
        'data': json.dumps(postObj),
    }
    res = requests.post(SERVER_URL, data=data)
    return_object = json.loads(res.content)
    report = decode_Report(return_object['list'])
    report_id_de = report[0]['report_id']
    report_content_de = report[0]['report_content']
    report_status_de = report[0]['report_status']
    vid_de = report[0]['vid_id']
    uid_de = report[0]['uid']

    if request.method=="POST": 
        report_id = request.POST.get('report_id')
        uid = request.POST.get('uid')
        vid = request.POST.get('vid')
        report_content = request.POST.get('report_content')
        report_status = request.POST.get('report_status')
        postObj = {
            'method_name': 'UPDATE_REPORT',
            'report_id': report_id,
            'uid': bs.encode_Str(uid),
            'vid_id': vid,
            'report_content': bs.encode_Str(report_content),
            'report_status': report_status, 
        }
        data = {
            'data': json.dumps(postObj),
        }
        res = requests.post(SERVER_URL, data=data)
        return_object = json.loads(res.content)
        return redirect('/report/'+str(vid)+'/report_main')

    context = { 'report_id':report_id_de, 'uid':uid_de, 'vid':vid_de, 'report_content':report_content_de, 'report_status':report_status_de }

    return render(request, 'report/detail_report.html', context)

@login_required(login_url='/login')
def delete_report(request, report_id):
    if request.method=="POST":
        postObj = {
            'method_name': 'DELETE_REPORT',
            'report_id': report_id,
        }
        data = {
            'data': json.dumps(postObj),
        }
        res = requests.post(SERVER_URL, data=data)
        return_object = json.loads(res.content)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

report/templates/report/detail_report.html
{% extends 'main.html' %}
{% block content %}
<style>
  input[type=text], select {
    width: 100%;
    padding: 10px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px; 
    box-sizing: border-box; 
  }
  
  input[type=submit] {
    width: 100%;
    color: white;
    padding: 15px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  
</style>
<div style="display: flex; width: 100%;   justify-content: center; " >
  <div class="card border-dark mb-3 bg-light" style="width: 50vw; border-style: dotted; margin-top:10px">
    <h5 class="card-header bg-dark text-white">Update The Report</h5>
    <div class="card-body ">
      <div>
        <form method="POST"> {% csrf_token %}
         
          <label for="report_id">Report ID</label>
          <input type="text" id="report_id" name="report_id" placeholder="Report ID" readonly="readonly" value="{{report_id}}">
      
          <label for="uid">User ID</label>
          <input type="text" id="uid" name="uid" placeholder="User ID" readonly="readonly" value="{{uid}}">

          <label for="vid">Video ID</label>
          <input type="text" id="vid" name="vid" placeholder="Video ID" readonly="readonly" value="{{vid}}">

          <label for="report_content">Report Content</label>
          <textarea name="report_content" class="form-control" id="report_content" placeholder="Report Content" rows="4" cols="50" >{{report_content}}</textarea>

          <label for="report_status">Report Status</label>
          <input type="text" id="report_status" name="report_status" placeholder="Report Status" value="{{report_status}}">
        
          <button type="submit" class="btn btn-primary" style='margin-top: 10px ;'>Save</button>
          <button type="button" class="btn btn-danger" onClick="javascript:history.go(-1);" style='margin-top: 10px ;'>Cancel</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

report/templates/report/home_report.html
{% extends 'main.html' %} 
{% load static %} 
{% block content %} 
<nav class="navbar bg-light" style="top: 1%;">
  <div class="container-fluid">
    <div class="dropdown">
        <select class="choice-type btn  btn-dark" name="type" select = "4" size = "1" onchange = "window.location.href =  this.value">
          <option value="{% url 'report:report_home' 0 %}"
            {% if video_type == 0%} selected = "selected" {%endif%}>All</option>
          <option value="{% url 'report:report_home' 1 %}"
            {% if video_type == 1%} selected = "selected" {%endif%}>Video</option>
          <option value="{% url 'report:report_home' 2 %}" 
            {% if video_type == 2%} selected = "selected" {%endif%}>Live TV</option>
          <option value="{% url 'report:report_home' 3 %}"
            {% if video_type == 3%} selected = "selected" {%endif%}>Radio</optoion>
        </select>
      </div>
    <form class="d-flex" role="search" method="GET" action="{% url 'report:report_home' video_type%}"> {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search or All" aria-label="Search" name="tv_search_video">
      <button class="btn btn-outline-success" type="submit" name="btn_search_video" style="margin-left:5px;">Search</button>
    </form>
  </div>
</nav>
<table class="table table_report" style = "overflow-y:scroll; height:75vh">
  <thead class="thead-light">
    <tr>
      <th scope="col">Video ID</th>
      <th scope="col">Video Title</th>
      <th scope="col">Total Reports</th>
      <th scope="col"></th>
    </tr>
  </thead>
  
  <tbody >
    {% for x in list_vids %}
    <tr>
      <td>{{x.vid_id}}</td>
      <td>{{x.vid_title}}</td>
      <td>{{x.total_reports}}</td>
      <td>
        <form action="{% url 'report:report_main' x.vid_id %}">
          <input type="image" class="icon_report" src="{% static 'styles/images/more.png' %}" />
        </form>
      </td>
    </tr>
  </tbody>
  {% endfor %} 
</table>
<nav aria-label="Page navigation example " style="margin-top: 10px;">
  <ul class="pagination">
    {% if list_vids.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_vids.previous_page_number}}">Previous</a></li>
    {% endif %}
    {% for i in nums %}
    <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}
    {% if list_vids.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{list_vids.next_page_number}}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_vids.paginator.num_pages}}">Last &raquo</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

report/templates/report/list_report.html
{% extends 'main.html' %} 
{% load static %} 
{% block content %} 
<nav class="navbar bg-light" style="top: 1%;">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold">{{num_reports}}</a>
    <form class="d-flex" role="search" method="GET" action="{% url 'report:report_main' video_id%}"> {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search or All" aria-label="Search" name="tv_search_report">
      <button class="btn btn-outline-success" type="submit" name="btn_search_report" style="margin-left:5px;">Search</button>
    </form>
  </div>
</nav>
<table class="table table_report" style = "overflow-y:scroll; height:80vh">
  <thead class="thead-light">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">User ID</th>
      <th scope="col">Report Content</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  
  <tbody>
    {% for report in list_res %}
    <tr>
      <td>{{report.report_id}}</td>
      <td>{{report.uid}}</td>
      <td>{{report.report_content}}</td>
      <td>{{report.report_status}}</td>
      <td>
        <form action="{% url 'report:detail_report' report.report_id %}">
          <input type="image" class="icon_report" src="{% static 'styles/images/edit.png' %}" />
        </form>
        
      </td>
      <td>
        <input type="image" class="icon_report" src="{% static 'styles/images/delete.png' %}" data-bs-toggle="modal" data-bs-target="#modal{{report.report_id}}" class="icon_report" />
          <div
            class="modal fade"
            id="modal{{report.report_id}}"
            tabindex="-1"
            role="dialog"
            aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true"
            
          >
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="a{{report.report_id}}">
                    Are you sure you want to delete?
                  </h5>
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">The report {{report.id}} of user {{report.uid}}</div>
                <div class="modal-footer">
                  <form action="{% url 'report:delete_report' report.report_id %}"  method="POST"> {% csrf_token %}
                  <button type="submit" class="btn btn-primary">Yes</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
      </td>
    </tr>
  </tbody>
  {% endfor %} 
</table>
<nav aria-label="Page navigation example " style="margin-top: 10px;">
  <ul class="pagination">
    {% if list_res.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_res.previous_page_number}}">Previous</a></li>
    {% endif %}
    {% for i in nums %}
    <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}
    {% if list_res.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{list_res.next_page_number}}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{list_res.paginator.num_pages}}">Last &raquo</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}