category/urls.py
from django.urls import path
from . import views
app_name = 'category'
urlpatterns = [
    path('category/<str:pk>/', views.category, name='category'),
    path('category-add/<str:pk>/', views.addCategory, name='add'),
    path('category-edit/<str:pk>/<str:id>', views.editCategory, name='edit'),
    path('category/<str:pk>/<str:id>', views.disableCategory, name='delcate'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('<int:video_type>/comment_home', views.comment_home, name = 'comment_home'),
    path('<int:video_id>/comment_main/', views.comment_main, name = 'comment_main'),
    path('<int:cmt_id>/delete/', views.delete_comment, name = 'delete_comment'),
    # path('<int:report_id>/update/', views.detail_report, name = 'detail_report'),
]

main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.login_view),
    path('logout/', views.logoutPage, name='logout'),
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('report/', include('report.urls')),
    path('category/', include('category.urls')),
    path('', include('managervideo.urls')),
    path('setting/', include('settingweb.urls')),
    path('comment/', include('comment.urls')),
    path('video/', include('videoapp.urls')),
    path('notification/', include('notification.urls')),
]

report/urls.py
from django.urls import path
from report import views

app_name = 'report'
urlpatterns = [
    path('<int:video_type>/report_home', views.report_home, name = 'report_home'),
    path('<int:video_id>/report_main/', views.report_main, name = 'report_main'),
    path('<int:report_id>/update/', views.detail_report, name = 'detail_report'),
    path('<int:report_id>/delete/', views.delete_report, name = 'delete_report'),
]

settingweb/urls.py
from django.urls import path
from . import views
app_name = 'settingweb'
urlpatterns = [
    path('setting/<str:able>/', views.settingweb, name='setting'),
    path('setting/update', views.updateSTW, name='update'),
    path('setting/choice/<str:type>/', views.choiceTrending, name='choice'),
]

main/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


def login_view(request):
    if(request.user.is_authenticated):
        return redirect("managervideo:managervideo", 1, 0)

    context = {}

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("managervideo:managervideo", 1, 0)
            else:
                messages.error(request, "Wrong password!")
        except:
            messages.error(request, "User is not exist!")

    return render(request, 'login.html', context)

@login_required(login_url='/login')
def logoutPage(request):
    logout(request)
    return redirect('/')

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link
            rel="stylesheet"
            type="text/css"
            media="screen"
            href="{% static 'styles/main.css' %}"
        />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
        />
    </head>
    <body style="background-color: #f0f8ff">

        
        
        <span class="login_container">
            <img src="{% static 'styles/images/login.png' %}" alt="" style="width:20%; height:40%; align:center">
            <div class="cardparent card">
                
                <div class="card-body">
                    <div>
                        
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="exampleInputUsername"
                                    >Username</label
                                >
                                <input
                                    type="text"
                                    name="username"
                                    class="form-control"
                                    placeholder="Enter Username"
                                />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1"
                                    >Password</label
                                >
                                <input
                                    type="password"
                                    name="password"
                                    class="form-control"
                                    id="exampleInputPassword1"
                                    placeholder="Password"
                                />
                            </div>
                            <button type="submit" class="btn btn-primary">
                                Login
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </span>
    </body>
</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            rel="stylesheet"
            type="text/css"
            media="screen"
            href="{% static 'styles/main.css' %}"
        />
        <link
            rel="stylesheet"
            type="image/png"
            media="screen"
            href="{% static 'styles/images' %}"
        />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    {% block style %}
    {% endblock style %}
    <title>{% block title %}Manager{% endblock title %}</title>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="maincontents">
      <div class="navcontain" >{% include 'navs.html' %}</div>
      <div class="container">
          {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'success' %}
              <div class="mt-2 alert alert-success" role="alert">
                {{ message }}
              </div>
            {% elif message.tags == 'error' %}
              <div class="mt-2 alert alert-danger" role="alert">
                {{ message }}
              </div>
            {% endif %}

            {% endfor %} 
          {% endif %}
          {% block content %} 
          {% endblock content %}
      </div>
  </div>
  </body>
</html>

templates/navs.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static 'styles/main.css' %}"
    />
    <link
      rel="stylesheet"
      type="image/png"
      media="screen"
      href="{% static 'styles/images' %}"
    />
  <title>Document</title>
</head>
<body>
  <nav class="navnhi nav bg-dark" >
    <ul class="ulnhi ">
      
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'managervideo:managervideo' pk=1 cat=0%}">Manager</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'category:category' 1 %}">Category</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'report:report_home' 0%}">Report</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'comment:comment_home' 0%}">Comment</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="https://console.firebase.google.com/u/0/project/watch-video-app-ffbc5/overview">User</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'settingweb:setting' 0%}">Setting</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'notification:send' %}">Push Notication</a>
      </li>
      <li class="nav-item">
        <a class="nhi nav-link" href="{% url 'main:logout' %}">Logout</a>
      </li>
    </ul>
  </nav>
  
</body>
</html>